Honor http2_max_pushed_streams setting
ghedo/http2-push-nginx-module pull request #3
Opened 2017-05-26 14:50 UTC by StephanDollberg

Don't push more than `http2_max_pushed_streams` resources. Setting
default to arbitrary value of 100.

2017-05-26 15:07 UTC, ghedo requested changes
Looks good, just a few minor things.

2017-05-26 15:07 UTC, ghedo commented on README.rst
> +
Should document default value (see e.g. `http2_server_push` docs).

2017-05-26 15:07 UTC, ghedo commented on src/ngx_http_v2_push_module.c
> +    if (ngx_http_v2_push_above_max_pushes(h2pscf, h2c)) {
Probably best to put this before the other check since it's less expensive. Not too important though.

2017-05-26 15:13 UTC, ghedo requested changes

2017-05-26 15:13 UTC, ghedo commented on src/ngx_http_v2_push_module.c
>        NGX_HTTP_MAIN_CONF|NGX_HTTP_SRV_CONF|NGX_CONF_FLAG,
I think `NGX_CONF_FLAG` needs to be changed to something else.

2017-05-26 15:15 UTC, ghedo commented on src/ngx_http_v2_push_module.c
>        NGX_HTTP_MAIN_CONF|NGX_HTTP_SRV_CONF|NGX_CONF_FLAG,
Probably `NGX_CONF_TAKE1`.

2017-05-26 15:20 UTC, StephanDollberg commented
Will fix the docs.

In regards to the check, yeah I am undecided on that.

Problem with checking for the length first is that if you were to push a
resource which you already pushed, then it returns an error even though
there is no real problem. (shrug)

On May 26, 2017 16:07, "Alessandro Ghedini" <notifications@github.com>
wrote:

*@ghedo* requested changes on this pull request.

Looks good, just a few minor things.
------------------------------

In README.rst
<https://github.com/ghedo/http2-push-nginx-module/pull/3#discussion_r118722756>
:

> @@ -32,6 +32,15 @@ http2_push_path

 Specifies a resource that should be pushed.

+http2_max_pushed_streams
+~~~~~~~~~~~~~~~
+
+**syntax:** *http2_max_pushed_streams <number>*
+

Should document default value (see e.g. http2_server_push docs).
------------------------------

In src/ngx_http_v2_push_module.c
<https://github.com/ghedo/http2-push-nginx-module/pull/3#discussion_r118723069>
:

> @@ -731,6 +746,10 @@ ngx_http_v2_push(ngx_http_request_t *r, u_char *u_str, size_t u_len)
         return NGX_OK;
     }

+    if (ngx_http_v2_push_above_max_pushes(h2pscf, h2c)) {

Probably best to put this before the other check since it's less expensive.
Not too important though.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ghedo/http2-push-nginx-module/pull/3#pullrequestreview-40544657>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/ACxSk5mRlH4xItEs-Rk7f_YnQgUbYHlfks5r9urEgaJpZM4NnsYr>
.

2017-05-30 08:44 UTC, StephanDollberg commented on README.rst
> +
fixed

2017-05-30 08:44 UTC, StephanDollberg commented on src/ngx_http_v2_push_module.c
> +    if (ngx_http_v2_push_above_max_pushes(h2pscf, h2c)) {
left this now as is

2017-05-30 08:44 UTC, StephanDollberg commented on src/ngx_http_v2_push_module.c
>        NGX_HTTP_MAIN_CONF|NGX_HTTP_SRV_CONF|NGX_CONF_FLAG,
`NGX_CONF_TAKE1` sounds about right, fixed

2017-05-31 23:24 UTC, ghedo approved these changes

2017-05-31 23:24 UTC, ghedo commented
Merged in 031acc46fd84907002fe2bf9bc7879e3c9d85fea, thanks!

2017-05-31 23:24 UTC, closed without merging